#!/bin/sh
# SPDX-License-Identifier: GPL-3.0-only
# Install the toolchain that rebuilds the Shockwave runtime: Node, Rust with the
# wasm32 target, and wasm-pack. Everything lands in vendor/toolchain, which is
# ignored by git and sits beside the other regenerable dependencies.
#
# This used to live in a hand-made directory under /tmp. macOS purges /tmp, and
# when it took half the npm install and part of the cargo registry with it the
# build failed in two different confusing ways — so the location is now stable
# and the install is repeatable.
#
#   sh Flashback/bootstrap-toolchain.sh          install what is missing
#   . Flashback/toolchain-env.sh                 put it on PATH for this shell
#
# Xcode is a separate prerequisite: the app needs Xcode's SwiftUI macro plugin,
# which the Command Line Tools alone do not ship. See "Build" in the README.
set -eu
cd "$(dirname "$0")/.."
root="$PWD/vendor/toolchain"
mkdir -p "$root"

NODE_VERSION=v24.21.0
WASM_PACK_VERSION=v0.15.0
case "$(uname -m)" in
    arm64) node_arch=darwin-arm64; wasm_arch=aarch64-apple-darwin ;;
    x86_64) node_arch=darwin-x64; wasm_arch=x86_64-apple-darwin ;;
    *) echo "Unsupported architecture: $(uname -m)" >&2; exit 1 ;;
esac

fetch() {
    # fetch URL DESTINATION
    if [ ! -f "$2" ]; then
        printf 'Downloading %s\n' "$(basename "$2")"
        curl --fail --location --progress-bar --output "$2.part" "$1"
        mv "$2.part" "$2"
    fi
}

node_dir="$root/node-$NODE_VERSION-$node_arch"
if [ ! -x "$node_dir/bin/node" ]; then
    archive="$root/node-$NODE_VERSION-$node_arch.tar.gz"
    fetch "https://nodejs.org/dist/$NODE_VERSION/node-$NODE_VERSION-$node_arch.tar.gz" "$archive"
    rm -rf "$node_dir"
    tar xzf "$archive" -C "$root"
fi

wasm_dir="$root/wasm-pack-$WASM_PACK_VERSION-$wasm_arch"
if [ ! -x "$wasm_dir/wasm-pack" ]; then
    archive="$root/wasm-pack-$WASM_PACK_VERSION-$wasm_arch.tar.gz"
    fetch "https://github.com/rustwasm/wasm-pack/releases/download/$WASM_PACK_VERSION/wasm-pack-$WASM_PACK_VERSION-$wasm_arch.tar.gz" "$archive"
    rm -rf "$wasm_dir"
    tar xzf "$archive" -C "$root"
fi

export RUSTUP_HOME="$root/rustup"
export CARGO_HOME="$root/cargo"
if [ ! -x "$CARGO_HOME/bin/cargo" ]; then
    fetch https://sh.rustup.rs "$root/rustup-init.sh"
    sh "$root/rustup-init.sh" -y --no-modify-path --profile minimal --default-toolchain stable
fi
"$CARGO_HOME/bin/rustup" target add wasm32-unknown-unknown

cat > "$PWD/Flashback/toolchain-env.sh" <<ENV
# Generated by bootstrap-toolchain.sh — source this before rebuild-shockwave.sh.
export RUSTUP_HOME="$root/rustup"
export CARGO_HOME="$root/cargo"
export CARGO_TARGET_DIR="$root/cargo-target"
export PATH="$root/cargo/bin:$node_dir/bin:$wasm_dir:\$PATH"
ENV

printf '\nInstalled in %s\n' "$root"
"$node_dir/bin/node" --version
"$CARGO_HOME/bin/cargo" --version
"$wasm_dir/wasm-pack" --version
printf '\nRun ". Flashback/toolchain-env.sh" before Flashback/rebuild-shockwave.sh.\n'
